/*
* generated by Xtext
*/
package gdsl.plugin;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GDSLStandaloneSetup extends GDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new GDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

