grammar gdsl.plugin.Terminals hidden(WS, ML_COMMENT, SL_COMMENT)
											
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

terminal ID : '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
terminal POSINT: ('0'..'9')+;
terminal NEGINT: '~'('1'..'9')('0'..'9')*;
terminal WS			: (' '|'\t'|'\r'|'\n')+;
terminal ML_COMMENT	: '(*' -> '*)';
terminal SL_COMMENT 	: '#' !('\n')* '\n';
