/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gdsl_rreil_BuilderBackend */

#ifndef _Included_gdsl_rreil_BuilderBackend
#define _Included_gdsl_rreil_BuilderBackend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gdsl_rreil_BuilderBackend
 * Method:    translate
 * Signature: (JJJ)Lgdsl/rreil/IRReilCollection;
 */
JNIEXPORT jobject JNICALL Java_gdsl_rreil_BuilderBackend_translate
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     gdsl_rreil_BuilderBackend
 * Method:    translateOptimizeBlock
 * Signature: (JJJLgdsl/translator/SemPres;)Lgdsl/rreil/IRReilCollection;
 */
JNIEXPORT jobject JNICALL Java_gdsl_rreil_BuilderBackend_translateOptimizeBlock
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
