/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gdsl_decoder_NativeInstruction */

#ifndef _Included_gdsl_decoder_NativeInstruction
#define _Included_gdsl_decoder_NativeInstruction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gdsl_decoder_NativeInstruction
 * Method:    size
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_gdsl_decoder_NativeInstruction_size
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     gdsl_decoder_NativeInstruction
 * Method:    pretty
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gdsl_decoder_NativeInstruction_pretty
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     gdsl_decoder_NativeInstruction
 * Method:    operands
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_gdsl_decoder_NativeInstruction_operands
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     gdsl_decoder_NativeInstruction
 * Method:    prettyOperand
 * Signature: (JJJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gdsl_decoder_NativeInstruction_prettyOperand
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     gdsl_decoder_NativeInstruction
 * Method:    operandType
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_gdsl_decoder_NativeInstruction_operandType
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     gdsl_decoder_NativeInstruction
 * Method:    mnemonic
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gdsl_decoder_NativeInstruction_mnemonic
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
