/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gdsl_Frontend */

#ifndef _Included_gdsl_Frontend
#define _Included_gdsl_Frontend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gdsl_Frontend
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gdsl_Frontend_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
