/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gdsl_Gdsl */

#ifndef _Included_gdsl_Gdsl
#define _Included_gdsl_Gdsl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gdsl_Gdsl
 * Method:    getFrontendsNative
 * Signature: ()[Lgdsl/Frontend;
 */
JNIEXPORT jobjectArray JNICALL Java_gdsl_Gdsl_getFrontendsNative
  (JNIEnv *, jobject);

/*
 * Class:     gdsl_Gdsl
 * Method:    getFrontendPtr
 * Signature: (Lgdsl/Frontend;)J
 */
JNIEXPORT jlong JNICALL Java_gdsl_Gdsl_getFrontendPtr
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gdsl_Gdsl
 * Method:    init
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_gdsl_Gdsl_init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gdsl_Gdsl
 * Method:    setCode
 * Signature: (JJLjava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_gdsl_Gdsl_setCode
  (JNIEnv *, jobject, jlong, jlong, jobject, jlong);

/*
 * Class:     gdsl_Gdsl
 * Method:    decodeOne
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_gdsl_Gdsl_decodeOne
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
