/**
 * generated by Xtext
 */
package gdsl.plugin.validation;

import gdsl.plugin.validation.AbstractGDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class GDSLValidator extends AbstractGDSLValidator {
}
