/*
* generated by Xtext
*/
package gdsl.plugin.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;


@Singleton
public class GDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDeclAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDeclDeclParserRuleCall_0_0 = (RuleCall)cDeclAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cSemicolonKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cDeclAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cDeclDeclParserRuleCall_1_1_0 = (RuleCall)cDeclAssignment_1_1.eContents().get(0);
		
		//Model:
		//	decl+=Decl (";"? decl+=Decl)*;
		public ParserRule getRule() { return rule; }

		//decl+=Decl (";"? decl+=Decl)*
		public Group getGroup() { return cGroup; }

		//decl+=Decl
		public Assignment getDeclAssignment_0() { return cDeclAssignment_0; }

		//Decl
		public RuleCall getDeclDeclParserRuleCall_0_0() { return cDeclDeclParserRuleCall_0_0; }

		//(";"? decl+=Decl)*
		public Group getGroup_1() { return cGroup_1; }

		//";"?
		public Keyword getSemicolonKeyword_1_0() { return cSemicolonKeyword_1_0; }

		//decl+=Decl
		public Assignment getDeclAssignment_1_1() { return cDeclAssignment_1_1; }

		//Decl
		public RuleCall getDeclDeclParserRuleCall_1_1_0() { return cDeclDeclParserRuleCall_1_1_0; }
	}

	public class DeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Decl");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDeclGranularityParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDeclExportParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDeclTypeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cDeclValParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//// *****************************
		//Decl:
		//	DeclGranularity | DeclExport | DeclType | DeclVal;
		public ParserRule getRule() { return rule; }

		//DeclGranularity | DeclExport | DeclType | DeclVal
		public Alternatives getAlternatives() { return cAlternatives; }

		//DeclGranularity
		public RuleCall getDeclGranularityParserRuleCall_0() { return cDeclGranularityParserRuleCall_0; }

		//DeclExport
		public RuleCall getDeclExportParserRuleCall_1() { return cDeclExportParserRuleCall_1; }

		//DeclType
		public RuleCall getDeclTypeParserRuleCall_2() { return cDeclTypeParserRuleCall_2; }

		//DeclVal
		public RuleCall getDeclValParserRuleCall_3() { return cDeclValParserRuleCall_3; }
	}

	public class DeclGranularityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DeclGranularity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameGranularityKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cGranularityAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cGranularityIntParserRuleCall_2_0 = (RuleCall)cGranularityAssignment_2.eContents().get(0);
		
		//// *****************************
		//DeclGranularity:
		//	name="granularity" "=" granularity=Int;
		public ParserRule getRule() { return rule; }

		//name="granularity" "=" granularity=Int
		public Group getGroup() { return cGroup; }

		//name="granularity"
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//"granularity"
		public Keyword getNameGranularityKeyword_0_0() { return cNameGranularityKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//granularity=Int
		public Assignment getGranularityAssignment_2() { return cGranularityAssignment_2; }

		//Int
		public RuleCall getGranularityIntParserRuleCall_2_0() { return cGranularityIntParserRuleCall_2_0; }
	}

	public class DeclExportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DeclExport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameExportKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cExportsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cExportsExportParserRuleCall_2_0 = (RuleCall)cExportsAssignment_2.eContents().get(0);
		
		//DeclExport:
		//	name="export" "=" exports+=Export*;
		public ParserRule getRule() { return rule; }

		//name="export" "=" exports+=Export*
		public Group getGroup() { return cGroup; }

		//name="export"
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//"export"
		public Keyword getNameExportKeyword_0_0() { return cNameExportKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//exports+=Export*
		public Assignment getExportsAssignment_2() { return cExportsAssignment_2; }

		//Export
		public RuleCall getExportsExportParserRuleCall_2_0() { return cExportsExportParserRuleCall_2_0; }
	}

	public class DeclTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DeclType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cTypeKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cValueAssignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final Alternatives cValueAlternatives_0_3_0 = (Alternatives)cValueAssignment_0_3.eContents().get(0);
		private final RuleCall cValueConDeclsParserRuleCall_0_3_0_0 = (RuleCall)cValueAlternatives_0_3_0.eContents().get(0);
		private final RuleCall cValueTyParserRuleCall_0_3_0_1 = (RuleCall)cValueAlternatives_0_3_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cTypeKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_1_0 = (RuleCall)cNameAssignment_1_1.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cAttrNameAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cAttrNameIDTerminalRuleCall_1_3_0 = (RuleCall)cAttrNameAssignment_1_3.eContents().get(0);
		private final Group cGroup_1_4 = (Group)cGroup_1.eContents().get(4);
		private final Keyword cCommaKeyword_1_4_0 = (Keyword)cGroup_1_4.eContents().get(0);
		private final Assignment cAttrNameAssignment_1_4_1 = (Assignment)cGroup_1_4.eContents().get(1);
		private final RuleCall cAttrNameIDTerminalRuleCall_1_4_1_0 = (RuleCall)cAttrNameAssignment_1_4_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_1_5 = (Keyword)cGroup_1.eContents().get(5);
		private final Keyword cEqualsSignKeyword_1_6 = (Keyword)cGroup_1.eContents().get(6);
		private final Assignment cValueAssignment_1_7 = (Assignment)cGroup_1.eContents().get(7);
		private final RuleCall cValueConDeclsParserRuleCall_1_7_0 = (RuleCall)cValueAssignment_1_7.eContents().get(0);
		
		//DeclType:
		//	"type" name=ID "=" value=(ConDecls | Ty) | "type" name=ID "[" attrName+=ID ("," attrName+=ID)* "]" "=" value=ConDecls;
		public ParserRule getRule() { return rule; }

		//"type" name=ID "=" value=(ConDecls | Ty) | "type" name=ID "[" attrName+=ID ("," attrName+=ID)* "]" "=" value=ConDecls
		public Alternatives getAlternatives() { return cAlternatives; }

		//"type" name=ID "=" value=(ConDecls | Ty)
		public Group getGroup_0() { return cGroup_0; }

		//"type"
		public Keyword getTypeKeyword_0_0() { return cTypeKeyword_0_0; }

		//name=ID
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_1_0() { return cNameIDTerminalRuleCall_0_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_0_2() { return cEqualsSignKeyword_0_2; }

		//value=(ConDecls | Ty)
		public Assignment getValueAssignment_0_3() { return cValueAssignment_0_3; }

		//ConDecls | Ty
		public Alternatives getValueAlternatives_0_3_0() { return cValueAlternatives_0_3_0; }

		//ConDecls
		public RuleCall getValueConDeclsParserRuleCall_0_3_0_0() { return cValueConDeclsParserRuleCall_0_3_0_0; }

		//Ty
		public RuleCall getValueTyParserRuleCall_0_3_0_1() { return cValueTyParserRuleCall_0_3_0_1; }

		//"type" name=ID "[" attrName+=ID ("," attrName+=ID)* "]" "=" value=ConDecls
		public Group getGroup_1() { return cGroup_1; }

		//"type"
		public Keyword getTypeKeyword_1_0() { return cTypeKeyword_1_0; }

		//name=ID
		public Assignment getNameAssignment_1_1() { return cNameAssignment_1_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_1_0() { return cNameIDTerminalRuleCall_1_1_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_1_2() { return cLeftSquareBracketKeyword_1_2; }

		//attrName+=ID
		public Assignment getAttrNameAssignment_1_3() { return cAttrNameAssignment_1_3; }

		//ID
		public RuleCall getAttrNameIDTerminalRuleCall_1_3_0() { return cAttrNameIDTerminalRuleCall_1_3_0; }

		//("," attrName+=ID)*
		public Group getGroup_1_4() { return cGroup_1_4; }

		//","
		public Keyword getCommaKeyword_1_4_0() { return cCommaKeyword_1_4_0; }

		//attrName+=ID
		public Assignment getAttrNameAssignment_1_4_1() { return cAttrNameAssignment_1_4_1; }

		//ID
		public RuleCall getAttrNameIDTerminalRuleCall_1_4_1_0() { return cAttrNameIDTerminalRuleCall_1_4_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_1_5() { return cRightSquareBracketKeyword_1_5; }

		//"="
		public Keyword getEqualsSignKeyword_1_6() { return cEqualsSignKeyword_1_6; }

		//value=ConDecls
		public Assignment getValueAssignment_1_7() { return cValueAssignment_1_7; }

		//ConDecls
		public RuleCall getValueConDeclsParserRuleCall_1_7_0() { return cValueConDeclsParserRuleCall_1_7_0; }
	}

	public class DeclValElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DeclVal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cValKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cAttrAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAttrIDTerminalRuleCall_2_0 = (RuleCall)cAttrAssignment_2.eContents().get(0);
		
		//DeclVal:
		//	"val" name=ID attr+=ID*;
		public ParserRule getRule() { return rule; }

		//"val" name=ID attr+=ID*
		public Group getGroup() { return cGroup; }

		//"val"
		public Keyword getValKeyword_0() { return cValKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//attr+=ID*
		public Assignment getAttrAssignment_2() { return cAttrAssignment_2; }

		//ID
		public RuleCall getAttrIDTerminalRuleCall_2_0() { return cAttrIDTerminalRuleCall_2_0; }
	}

	public class ExportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Export");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameQidParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cAttrNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cAttrNameIDTerminalRuleCall_1_1_0 = (RuleCall)cAttrNameAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cAttrNameAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cAttrNameIDTerminalRuleCall_1_2_1_0 = (RuleCall)cAttrNameAssignment_1_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//// *****************************
		//Export:
		//	name=Qid ("{" attrName+=ID ("," attrName+=ID)* "}")?;
		public ParserRule getRule() { return rule; }

		//name=Qid ("{" attrName+=ID ("," attrName+=ID)* "}")?
		public Group getGroup() { return cGroup; }

		//name=Qid
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//Qid
		public RuleCall getNameQidParserRuleCall_0_0() { return cNameQidParserRuleCall_0_0; }

		//("{" attrName+=ID ("," attrName+=ID)* "}")?
		public Group getGroup_1() { return cGroup_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1_0() { return cLeftCurlyBracketKeyword_1_0; }

		//attrName+=ID
		public Assignment getAttrNameAssignment_1_1() { return cAttrNameAssignment_1_1; }

		//ID
		public RuleCall getAttrNameIDTerminalRuleCall_1_1_0() { return cAttrNameIDTerminalRuleCall_1_1_0; }

		//("," attrName+=ID)*
		public Group getGroup_1_2() { return cGroup_1_2; }

		//","
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }

		//attrName+=ID
		public Assignment getAttrNameAssignment_1_2_1() { return cAttrNameAssignment_1_2_1; }

		//ID
		public RuleCall getAttrNameIDTerminalRuleCall_1_2_1_0() { return cAttrNameIDTerminalRuleCall_1_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_1_3() { return cRightCurlyBracketKeyword_1_3; }
	}

	public class ConDeclsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConDecls");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cConDeclsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cConDeclsConDeclParserRuleCall_0_0 = (RuleCall)cConDeclsAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cVerticalLineKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cConDeclsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cConDeclsConDeclParserRuleCall_1_1_0 = (RuleCall)cConDeclsAssignment_1_1.eContents().get(0);
		
		//ConDecls:
		//	conDecls+=ConDecl ("|" conDecls+=ConDecl)*;
		public ParserRule getRule() { return rule; }

		//conDecls+=ConDecl ("|" conDecls+=ConDecl)*
		public Group getGroup() { return cGroup; }

		//conDecls+=ConDecl
		public Assignment getConDeclsAssignment_0() { return cConDeclsAssignment_0; }

		//ConDecl
		public RuleCall getConDeclsConDeclParserRuleCall_0_0() { return cConDeclsConDeclParserRuleCall_0_0; }

		//("|" conDecls+=ConDecl)*
		public Group getGroup_1() { return cGroup_1; }

		//"|"
		public Keyword getVerticalLineKeyword_1_0() { return cVerticalLineKeyword_1_0; }

		//conDecls+=ConDecl
		public Assignment getConDeclsAssignment_1_1() { return cConDeclsAssignment_1_1; }

		//ConDecl
		public RuleCall getConDeclsConDeclParserRuleCall_1_1_0() { return cConDeclsConDeclParserRuleCall_1_1_0; }
	}

	public class ConDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConDecl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameConBindParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cOfKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cTyAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cTyTyParserRuleCall_1_1_0 = (RuleCall)cTyAssignment_1_1.eContents().get(0);
		
		//ConDecl:
		//	name=ConBind ("of" ty=Ty)?;
		public ParserRule getRule() { return rule; }

		//name=ConBind ("of" ty=Ty)?
		public Group getGroup() { return cGroup; }

		//name=ConBind
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ConBind
		public RuleCall getNameConBindParserRuleCall_0_0() { return cNameConBindParserRuleCall_0_0; }

		//("of" ty=Ty)?
		public Group getGroup_1() { return cGroup_1; }

		//"of"
		public Keyword getOfKeyword_1_0() { return cOfKeyword_1_0; }

		//ty=Ty
		public Assignment getTyAssignment_1_1() { return cTyAssignment_1_1; }

		//Ty
		public RuleCall getTyTyParserRuleCall_1_1_0() { return cTyTyParserRuleCall_1_1_0; }
	}

	public class TyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Ty");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cValueIntParserRuleCall_0_0 = (RuleCall)cValueAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cVerticalLineKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cValueAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cValueIntParserRuleCall_1_1_0 = (RuleCall)cValueAssignment_1_1.eContents().get(0);
		private final Keyword cVerticalLineKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Assignment cValueAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cValueQidParserRuleCall_2_0_0 = (RuleCall)cValueAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cTyBindAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cTyBindTyBindParserRuleCall_2_1_1_0 = (RuleCall)cTyBindAssignment_2_1_1.eContents().get(0);
		private final Group cGroup_2_1_2 = (Group)cGroup_2_1.eContents().get(2);
		private final Keyword cCommaKeyword_2_1_2_0 = (Keyword)cGroup_2_1_2.eContents().get(0);
		private final Assignment cTyBindAssignment_2_1_2_1 = (Assignment)cGroup_2_1_2.eContents().get(1);
		private final RuleCall cTyBindTyBindParserRuleCall_2_1_2_1_0 = (RuleCall)cTyBindAssignment_2_1_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_1_3 = (Keyword)cGroup_2_1.eContents().get(3);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cElementsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cElementsTyElementParserRuleCall_3_1_0 = (RuleCall)cElementsAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cElementsAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cElementsTyElementParserRuleCall_3_2_1_0 = (RuleCall)cElementsAssignment_3_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_3 = (Keyword)cGroup_3.eContents().get(3);
		
		//Ty:
		//	value=Int | "|" value=Int "|" | value=Qid ("[" tyBind+=TyBind ("," tyBind+=TyBind)* "]")? | "{" elements+=TyElement
		//	("," elements+=TyElement)* "}";
		public ParserRule getRule() { return rule; }

		//value=Int | "|" value=Int "|" | value=Qid ("[" tyBind+=TyBind ("," tyBind+=TyBind)* "]")? | "{" elements+=TyElement (","
		//elements+=TyElement)* "}"
		public Alternatives getAlternatives() { return cAlternatives; }

		//value=Int
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }

		//Int
		public RuleCall getValueIntParserRuleCall_0_0() { return cValueIntParserRuleCall_0_0; }

		//"|" value=Int "|"
		public Group getGroup_1() { return cGroup_1; }

		//"|"
		public Keyword getVerticalLineKeyword_1_0() { return cVerticalLineKeyword_1_0; }

		//value=Int
		public Assignment getValueAssignment_1_1() { return cValueAssignment_1_1; }

		//Int
		public RuleCall getValueIntParserRuleCall_1_1_0() { return cValueIntParserRuleCall_1_1_0; }

		//"|"
		public Keyword getVerticalLineKeyword_1_2() { return cVerticalLineKeyword_1_2; }

		//value=Qid ("[" tyBind+=TyBind ("," tyBind+=TyBind)* "]")?
		public Group getGroup_2() { return cGroup_2; }

		//value=Qid
		public Assignment getValueAssignment_2_0() { return cValueAssignment_2_0; }

		//Qid
		public RuleCall getValueQidParserRuleCall_2_0_0() { return cValueQidParserRuleCall_2_0_0; }

		//("[" tyBind+=TyBind ("," tyBind+=TyBind)* "]")?
		public Group getGroup_2_1() { return cGroup_2_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_2_1_0() { return cLeftSquareBracketKeyword_2_1_0; }

		//tyBind+=TyBind
		public Assignment getTyBindAssignment_2_1_1() { return cTyBindAssignment_2_1_1; }

		//TyBind
		public RuleCall getTyBindTyBindParserRuleCall_2_1_1_0() { return cTyBindTyBindParserRuleCall_2_1_1_0; }

		//("," tyBind+=TyBind)*
		public Group getGroup_2_1_2() { return cGroup_2_1_2; }

		//","
		public Keyword getCommaKeyword_2_1_2_0() { return cCommaKeyword_2_1_2_0; }

		//tyBind+=TyBind
		public Assignment getTyBindAssignment_2_1_2_1() { return cTyBindAssignment_2_1_2_1; }

		//TyBind
		public RuleCall getTyBindTyBindParserRuleCall_2_1_2_1_0() { return cTyBindTyBindParserRuleCall_2_1_2_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_2_1_3() { return cRightSquareBracketKeyword_2_1_3; }

		//"{" elements+=TyElement ("," elements+=TyElement)* "}"
		public Group getGroup_3() { return cGroup_3; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_0() { return cLeftCurlyBracketKeyword_3_0; }

		//elements+=TyElement
		public Assignment getElementsAssignment_3_1() { return cElementsAssignment_3_1; }

		//TyElement
		public RuleCall getElementsTyElementParserRuleCall_3_1_0() { return cElementsTyElementParserRuleCall_3_1_0; }

		//("," elements+=TyElement)*
		public Group getGroup_3_2() { return cGroup_3_2; }

		//","
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }

		//elements+=TyElement
		public Assignment getElementsAssignment_3_2_1() { return cElementsAssignment_3_2_1; }

		//TyElement
		public RuleCall getElementsTyElementParserRuleCall_3_2_1_0() { return cElementsTyElementParserRuleCall_3_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_3() { return cRightCurlyBracketKeyword_3_3; }
	}

	public class TyElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TyElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueTyParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//TyElement:
		//	name=ID ":" value=Ty;
		public ParserRule getRule() { return rule; }

		//name=ID ":" value=Ty
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//value=Ty
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//Ty
		public RuleCall getValueTyParserRuleCall_2_0() { return cValueTyParserRuleCall_2_0; }
	}

	public class TyBindElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TyBind");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKeyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cKeyQidParserRuleCall_0_0 = (RuleCall)cKeyAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cValueAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cValueTyParserRuleCall_1_1_0 = (RuleCall)cValueAssignment_1_1.eContents().get(0);
		
		//TyBind:
		//	key=Qid ("=" value=Ty)?;
		public ParserRule getRule() { return rule; }

		//key=Qid ("=" value=Ty)?
		public Group getGroup() { return cGroup; }

		//key=Qid
		public Assignment getKeyAssignment_0() { return cKeyAssignment_0; }

		//Qid
		public RuleCall getKeyQidParserRuleCall_0_0() { return cKeyQidParserRuleCall_0_0; }

		//("=" value=Ty)?
		public Group getGroup_1() { return cGroup_1; }

		//"="
		public Keyword getEqualsSignKeyword_1_0() { return cEqualsSignKeyword_1_0; }

		//value=Ty
		public Assignment getValueAssignment_1_1() { return cValueAssignment_1_1; }

		//Ty
		public RuleCall getValueTyParserRuleCall_1_1_0() { return cValueTyParserRuleCall_1_1_0; }
	}

	public class ConBindElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConBind");
		private final RuleCall cCONSTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		////DataType Rules
		//ConBind:
		//	CONS;
		public ParserRule getRule() { return rule; }

		//CONS
		public RuleCall getCONSTerminalRuleCall() { return cCONSTerminalRuleCall; }
	}

	public class IntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Int");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPOSINTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cNEGINTTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Int:
		//	POSINT | NEGINT;
		public ParserRule getRule() { return rule; }

		//POSINT | NEGINT
		public Alternatives getAlternatives() { return cAlternatives; }

		//POSINT
		public RuleCall getPOSINTTerminalRuleCall_0() { return cPOSINTTerminalRuleCall_0; }

		//NEGINT
		public RuleCall getNEGINTTerminalRuleCall_1() { return cNEGINTTerminalRuleCall_1; }
	}

	public class QidElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Qid");
		private final RuleCall cIDTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Qid:
		//	ID;
		public ParserRule getRule() { return rule; }

		//ID
		public RuleCall getIDTerminalRuleCall() { return cIDTerminalRuleCall; }
	}
	
	
	private ModelElements pModel;
	private DeclElements pDecl;
	private DeclGranularityElements pDeclGranularity;
	private DeclExportElements pDeclExport;
	private DeclTypeElements pDeclType;
	private DeclValElements pDeclVal;
	private ExportElements pExport;
	private ConDeclsElements pConDecls;
	private ConDeclElements pConDecl;
	private TyElements pTy;
	private TyElementElements pTyElement;
	private TyBindElements pTyBind;
	private ConBindElements pConBind;
	private IntElements pInt;
	private QidElements pQid;
	private TerminalRule tCONS;
	private TerminalRule tID;
	private TerminalRule tPOSINT;
	private TerminalRule tNEGINT;
	private TerminalRule tML_COMMENT;
	private TerminalRule tSL_COMMENT;
	private TerminalRule tWS;
	
	private final Grammar grammar;

	@Inject
	public GDSLGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("gdsl.plugin.GDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//Model:
	//	decl+=Decl (";"? decl+=Decl)*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//// *****************************
	//Decl:
	//	DeclGranularity | DeclExport | DeclType | DeclVal;
	public DeclElements getDeclAccess() {
		return (pDecl != null) ? pDecl : (pDecl = new DeclElements());
	}
	
	public ParserRule getDeclRule() {
		return getDeclAccess().getRule();
	}

	//// *****************************
	//DeclGranularity:
	//	name="granularity" "=" granularity=Int;
	public DeclGranularityElements getDeclGranularityAccess() {
		return (pDeclGranularity != null) ? pDeclGranularity : (pDeclGranularity = new DeclGranularityElements());
	}
	
	public ParserRule getDeclGranularityRule() {
		return getDeclGranularityAccess().getRule();
	}

	//DeclExport:
	//	name="export" "=" exports+=Export*;
	public DeclExportElements getDeclExportAccess() {
		return (pDeclExport != null) ? pDeclExport : (pDeclExport = new DeclExportElements());
	}
	
	public ParserRule getDeclExportRule() {
		return getDeclExportAccess().getRule();
	}

	//DeclType:
	//	"type" name=ID "=" value=(ConDecls | Ty) | "type" name=ID "[" attrName+=ID ("," attrName+=ID)* "]" "=" value=ConDecls;
	public DeclTypeElements getDeclTypeAccess() {
		return (pDeclType != null) ? pDeclType : (pDeclType = new DeclTypeElements());
	}
	
	public ParserRule getDeclTypeRule() {
		return getDeclTypeAccess().getRule();
	}

	//DeclVal:
	//	"val" name=ID attr+=ID*;
	public DeclValElements getDeclValAccess() {
		return (pDeclVal != null) ? pDeclVal : (pDeclVal = new DeclValElements());
	}
	
	public ParserRule getDeclValRule() {
		return getDeclValAccess().getRule();
	}

	//// *****************************
	//Export:
	//	name=Qid ("{" attrName+=ID ("," attrName+=ID)* "}")?;
	public ExportElements getExportAccess() {
		return (pExport != null) ? pExport : (pExport = new ExportElements());
	}
	
	public ParserRule getExportRule() {
		return getExportAccess().getRule();
	}

	//ConDecls:
	//	conDecls+=ConDecl ("|" conDecls+=ConDecl)*;
	public ConDeclsElements getConDeclsAccess() {
		return (pConDecls != null) ? pConDecls : (pConDecls = new ConDeclsElements());
	}
	
	public ParserRule getConDeclsRule() {
		return getConDeclsAccess().getRule();
	}

	//ConDecl:
	//	name=ConBind ("of" ty=Ty)?;
	public ConDeclElements getConDeclAccess() {
		return (pConDecl != null) ? pConDecl : (pConDecl = new ConDeclElements());
	}
	
	public ParserRule getConDeclRule() {
		return getConDeclAccess().getRule();
	}

	//Ty:
	//	value=Int | "|" value=Int "|" | value=Qid ("[" tyBind+=TyBind ("," tyBind+=TyBind)* "]")? | "{" elements+=TyElement
	//	("," elements+=TyElement)* "}";
	public TyElements getTyAccess() {
		return (pTy != null) ? pTy : (pTy = new TyElements());
	}
	
	public ParserRule getTyRule() {
		return getTyAccess().getRule();
	}

	//TyElement:
	//	name=ID ":" value=Ty;
	public TyElementElements getTyElementAccess() {
		return (pTyElement != null) ? pTyElement : (pTyElement = new TyElementElements());
	}
	
	public ParserRule getTyElementRule() {
		return getTyElementAccess().getRule();
	}

	//TyBind:
	//	key=Qid ("=" value=Ty)?;
	public TyBindElements getTyBindAccess() {
		return (pTyBind != null) ? pTyBind : (pTyBind = new TyBindElements());
	}
	
	public ParserRule getTyBindRule() {
		return getTyBindAccess().getRule();
	}

	////DataType Rules
	//ConBind:
	//	CONS;
	public ConBindElements getConBindAccess() {
		return (pConBind != null) ? pConBind : (pConBind = new ConBindElements());
	}
	
	public ParserRule getConBindRule() {
		return getConBindAccess().getRule();
	}

	//Int:
	//	POSINT | NEGINT;
	public IntElements getIntAccess() {
		return (pInt != null) ? pInt : (pInt = new IntElements());
	}
	
	public ParserRule getIntRule() {
		return getIntAccess().getRule();
	}

	//Qid:
	//	ID;
	public QidElements getQidAccess() {
		return (pQid != null) ? pQid : (pQid = new QidElements());
	}
	
	public ParserRule getQidRule() {
		return getQidAccess().getRule();
	}

	////Terminal symbols	
	////TODO
	//terminal CONS:
	//	"constodo";
	public TerminalRule getCONSRule() {
		return (tCONS != null) ? tCONS : (tCONS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "CONS"));
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return (tID != null) ? tID : (tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ID"));
	} 

	//terminal POSINT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getPOSINTRule() {
		return (tPOSINT != null) ? tPOSINT : (tPOSINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "POSINT"));
	} 

	//terminal NEGINT:
	//	"~" "1".."9" "0".."9"*;
	public TerminalRule getNEGINTRule() {
		return (tNEGINT != null) ? tNEGINT : (tNEGINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NEGINT"));
	} 

	//terminal ML_COMMENT:
	//	"(*"->"*)";
	public TerminalRule getML_COMMENTRule() {
		return (tML_COMMENT != null) ? tML_COMMENT : (tML_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ML_COMMENT"));
	} 

	//terminal SL_COMMENT:
	//	"#" !"\n"* "\n";
	public TerminalRule getSL_COMMENTRule() {
		return (tSL_COMMENT != null) ? tSL_COMMENT : (tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SL_COMMENT"));
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return (tWS != null) ? tWS : (tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WS"));
	} 
}
