/*
 * generated by Xtext
 */
package gdsl.plugin.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GDSLUiModule extends gdsl.plugin.ui.AbstractGDSLUiModule {
	public GDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
