/*
* generated by Xtext
*/
package gdsl.plugin;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return gdsl.plugin.ui.internal.GDSLActivator.getInstance().getInjector("gdsl.plugin.GDSL");
	}
	
}
