/*
 * generated by Xtext
 */
package gdsl.plugin.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractGDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(gdsl.plugin.gDSL.GDSLPackage.eINSTANCE);
		return result;
	}
}
