val revision/traverse f insn = 
   case insn of
      ADDIUPC x: f "ADDIUPC" (BINOP_LR x)
    | ALIGN x: f "ALIGN" (QUADOP_LRRR x)
    | ALUIPC x: f "ALUIPC" (BINOP_LR x)
    | AUI x: f "AUI" (TERNOP_LRR x)
    | AUIPC x: f "AUIPC" (BINOP_LR x)
    | BALC x: f "BALC" (UNOP_R x)
    | BC x: f "BC" (UNOP_R x)
    | BC1EQZ x: f "BC1EQZ" (BINOP_RR x)
    | BC1NEZ x: f "BC1NEZ" (BINOP_RR x)
    | BC2EQZ x: f "BC2EQZ" (BINOP_RR x)
    | BC2NEZ x: f "BC2NEZ" (BINOP_RR x)
    | BLEZALC x: f "BLEZALC" (BINOP_RR x)
    | BGEZALC x: f "BGEZALC" (BINOP_RR x)
    | BGTZALC x: f "BGTZALC" (BINOP_RR x)
    | BLTZALC x: f "BLTZALC" (BINOP_RR x)
    | BEQZALC x: f "BEQZALC" (BINOP_RR x)
    | BNEZALC x: f "BNEZALC" (BINOP_RR x)
   end
