val uarity-of insn = let
  val f a b = b
in
  traverse f insn
end

val mnemonic-of insn = let
  val f a b = a
in
  traverse f insn
end

# -> sftl
type uarity =
   NULLOP
 | UNOP_R of unop-r
 | UNOP_L of unop-l
 | BINOP_RR of binop-rr
 | BINOP_RL of binop-rl
 | BINOP_LR of binop-lr
 | BINOP_FLR of binop-flr
 | TERNOP_RRR of ternop-rrr
 | TERNOP_LRR of ternop-lrr
 | TERNOP_FLRR of ternop-flrr
 | TERNOP_CFLRR of ternop-cflrr
 | QUADOP_LRRR of quadop-lrrr
 | QUADOP_FLRRR of quadop-flrrr


val traverse f insn = 
   case insn of
      UNPREDICTABLE: f "UNPREDICTABLE" (NULLOP)
    | ABS-fmt x: f "ABS" (BINOP_FLR x)
    | ADD x: f "ADD" (TERNOP_LRR x)
    | ADD-fmt x: f "ADD" (TERNOP_FLRR x)
    | ADDI x: f "ADDI" (TERNOP_LRR x)
    | ADDIU x: f "ADDIU" (TERNOP_LRR x)
    | ADDU x: f "ADDU" (TERNOP_LRR x)
    | ALNV-PS x: f "ALNV.PS" (QUADOP_LRRR x)
    | AND x: f "AND" (TERNOP_LRR x)
    | ANDI x: f "ANDI" (TERNOP_LRR x)
    | BC1F x: f "BC1F" (BINOP_RR x)
    | BC1FL x: f "BC1FL" (BINOP_RR x)
    | BC1T x: f "BC1T" (BINOP_RR x)
    | BC1TL x: f "BC1TL" (BINOP_RR x)
    | BC2F x: f "BC2F" (BINOP_RR x)
    | BC2FL x: f "BC2FL" (BINOP_RR x)
    | BC2T x: f "BC2T" (BINOP_RR x)
    | BC2TL x: f "BC2TL" (BINOP_RR x)
    | BEQ x: f "BEQ" (TERNOP_RRR x)
    | BEQL x: f "BEQL" (TERNOP_RRR x)
    | BGEZ x: f "BGEZ" (BINOP_RR x)
    | BGEZAL x: f "BGEZAL" (BINOP_RR x)
    | BGEZALL x: f "BGEZALL" (BINOP_RR x)
    | BGEZL x: f "BGEZL" (BINOP_RR x)
    | BGTZ x: f "BGTZ" (BINOP_RR x)
    | BGTZL x: f "BGTZL" (BINOP_RR x)
    | BLEZ x: f "BLEZ" (BINOP_RR x)
    | BLEZL x: f "BLEZL" (BINOP_RR x)
    | BLTZ x: f "BLTZ" (BINOP_RR x)
    | BLTZAL x: f "BLTZAL" (BINOP_RR x)
    | BLTZALL x: f "BLTZALL" (BINOP_RR x)
    | BLTZL x: f "BLTZL" (BINOP_RR x)
    | BNE x: f "BNE" (TERNOP_RRR x)
    | BNEL x: f "BNEL" (TERNOP_RRR x)
    | BREAK x: f "BREAK" (UNOP_R x)
    | C-cond-fmt x: f "C" (TERNOP_CFLRR x)
    | CACHE x: f "CACHE" (TERNOP_RRR x)
    | CACHEE x: f "CACHEE" (TERNOP_RRR x)
    | CEIL-L-fmt x: f "CEIL.L" (BINOP_FLR x)
    | CEIL-W-fmt x: f "CEIL.W" (BINOP_FLR x)
    | CFC1 x: f "CFC1" (BINOP_LR x)
    | CFC2 x: f "CFC2" (BINOP_LR x)
    | CLO x: f "CLO" (BINOP_LR x)
    | CLZ x: f "CLZ" (BINOP_LR x)
    | COP2 x: f "COP2" (UNOP_R x)
    | CTC1 x: f "CTC1" (BINOP_RR x)
    | CTC2 x: f "CTC2" (BINOP_RR x)
    | CVT-D-fmt x: f "CVT.D" (BINOP_FLR x)
    | CVT-L-fmt x: f "CVT.L" (BINOP_FLR x)
    | CVT-PS-S x: f "CVT.PS.S" (TERNOP_LRR x)
    | CVT-S-fmt x: f "CVT.S" (BINOP_FLR x)
    | CVT-S-PL x: f "CVT.S.PL" (BINOP_LR x)
    | CVT-S-PU x: f "CVT.S.PU" (BINOP_LR x)
    | CVT-W-fmt x: f "CVT.W" (BINOP_FLR x)
    | DERET: f "DERET" (NULLOP)
    | DI x: f "DI" (UNOP_L x)
    | DIV x: f "DIV" (BINOP_RR x)
    | DIV-fmt x: f "DIV" (TERNOP_FLRR x)
    | DIVU x: f "DIVU" (BINOP_RR x)
    | EI x: f "EI" (UNOP_L x)
    | ERET: f "ERET" (NULLOP)
    | EXT x: f "EXT" (QUADOP_LRRR x)
    | FLOOR-L-fmt x: f "FLOOR.L" (BINOP_FLR x)
    | FLOOR-W-fmt x: f "FLOOR.W" (BINOP_FLR x)
    | INS x: f "INS" (QUADOP_LRRR x)
    | J x: f "J" (UNOP_R x)
    | JAL x: f "JAL" (UNOP_R x)
    | JALR x: f "JALR" (BINOP_LR x)
    | JALR-HB x: f "JALR.HB" (BINOP_LR x)
    | JALX x: f "JALX" (UNOP_R x)
    | JR x: f "JR" (UNOP_R x)
    | JR-HB x: f "JR.HB" (UNOP_R x)
    | LB x: f "LB" (BINOP_LR x)
    | LBE x: f "LBE" (BINOP_LR x)
    | LBU x: f "LBU" (BINOP_LR x)
    | LBUE x: f "LBUE" (BINOP_LR x)
    | LDC1 x: f "LDC1" (BINOP_LR x)
    | LDC2 x: f "LDC2" (BINOP_RR x)
    | LDXC1 x: f "LDXC1" (BINOP_LR x)
    | LH x: f "LH" (BINOP_LR x)
    | LHE x: f "LHE" (BINOP_LR x)
    | LHU x: f "LHU" (BINOP_LR x)
    | LHUE x: f "LHUE" (BINOP_LR x)
    | LL x: f "LL" (BINOP_LR x)
    | LLE x: f "LLE" (BINOP_LR x)
    | LUI x: f "LUI" (BINOP_LR x)
    | LUXC1 x: f "LUXC1" (BINOP_LR x)
    | LW x: f "LW" (BINOP_LR x)
    | LWC1 x: f "LWC1" (BINOP_LR x)
    | LWC2 x: f "LWC2" (BINOP_RR x)
    | LWE x: f "LWE" (BINOP_LR x)
    | LWL x: f "LWL" (BINOP_LR x)
    | LWLE x: f "LWLE" (BINOP_LR x)
    | LWR x: f "LWR" (BINOP_LR x)
    | LWRE x: f "LWRE" (BINOP_LR x)
    | LWXC1 x: f "LWXC1" (BINOP_LR x)
    | MADD x: f "MADD" (BINOP_RR x)
    | MADD-fmt x: f "MADD" (QUADOP_FLRRR x)
    | MADDU x: f "MADDU" (BINOP_RR x)
    | MFC0 x: f "MFC0" (TERNOP_LRR x)
    | MFC1 x: f "MFC1" (BINOP_LR x)
    | MFC2 x: f "MFC2" (BINOP_LR x)
    | MFHC1 x: f "MFHC1" (BINOP_LR x)
    | MFHC2 x: f "MFHC2" (BINOP_LR x)
    | MFHI x: f "MFHI" (UNOP_L x)
    | MFLO x: f "MFLO" (UNOP_L x)
    | MOV-fmt x: f "MOV" (BINOP_FLR x)
    | MOVF x: f "MOVF" (TERNOP_LRR x)
    | MOVF-fmt x: f "MOVF" (TERNOP_FLRR x)
    | MOVN x: f "MOVN" (TERNOP_LRR x)
    | MOVN-fmt x: f "MOVN" (TERNOP_FLRR x)
    | MOVT x: f "MOVT" (TERNOP_LRR x)
    | MOVT-fmt x: f "MOVT" (TERNOP_FLRR x)
    | MOVZ x: f "MOVZ" (TERNOP_LRR x)
    | MOVZ-fmt x: f "MOVZ" (TERNOP_FLRR x)
    | MSUB x: f "MSUB" (BINOP_RR x)
    | MSUB-fmt x: f "MSUB" (QUADOP_FLRRR x)
    | MSUBU x: f "MSUBU" (BINOP_RR x)
    | MTC0 x: f "MTC0" (TERNOP_RRR x)
    | MTC1 x: f "MTC1" (BINOP_RL x)
    | MTC2 x: f "MTC2" (BINOP_RR x)
    | MTHC1 x: f "MTHC1" (BINOP_RL x)
    | MTHC2 x: f "MTHC2" (BINOP_RR x)
    | MTHI x: f "MTHI" (UNOP_R x)
    | MTLO x: f "MTLO" (UNOP_R x)
    | MUL x: f "MUL" (TERNOP_LRR x)
    | MUL-fmt x: f "MUL" (TERNOP_FLRR x)
    | MULT x: f "MULT" (BINOP_RR x)
    | MULTU x: f "MULTU" (BINOP_RR x)
    | NEG-fmt x: f "NEG" (BINOP_FLR x)
    | NMADD-fmt x: f "NMADD" (QUADOP_FLRRR x)
    | NMSUB-fmt x: f "NMSUB" (QUADOP_FLRRR x)
    | NOR x: f "NOR" (TERNOP_LRR x)
    | OR x: f "OR" (TERNOP_LRR x)
    | ORI x: f "ORI" (TERNOP_LRR x)
    | PAUSE: f "PAUSE" (NULLOP)
    | PLL-PS x: f "PLL.PS" (TERNOP_LRR x)
    | PLU-PS x: f "PLU.PS" (TERNOP_LRR x)
    | PREF x: f "PREF" (TERNOP_RRR x)
    | PREFE x: f "PREFE" (TERNOP_RRR x)
    | PREFX x: f "PREFX" (TERNOP_RRR x)
    | PUL-PS x: f "PUL.PS" (TERNOP_LRR x)
    | PUU-PS x: f "PUU.PS" (TERNOP_LRR x)
    | RDHWR x: f "RDHWR" (BINOP_LR x)
    | RDPGPR x: f "RDPGPR" (BINOP_LR x)
    | RECIP-fmt x: f "RECIP" (BINOP_FLR x)
    | ROTR x: f "ROTR" (TERNOP_LRR x)
    | ROTRV x: f "ROTRV" (TERNOP_LRR x)
    | ROUND-L-fmt x: f "ROUND.L" (BINOP_FLR x)
    | ROUND-W-fmt x: f "ROUND.W" (BINOP_FLR x)
    | RSQRT-fmt x: f "RSQRT" (BINOP_FLR x)
    | SB x: f "SB" (BINOP_RR x)
    | SBE x: f "SBE" (BINOP_RR x)
    | SC x: f "SC" (BINOP_LR x)
    | SCE x: f "SCE" (BINOP_LR x)
    | SDBBP x: f "SDBBP" (UNOP_R x)
    | SDC1 x: f "SDC1" (BINOP_RR x)
    | SDC2 x: f "SDC2" (BINOP_RR x)
    | SDXC1 x: f "SDXC1" (BINOP_RR x)
    | SEB x: f "SEB" (BINOP_LR x)
    | SEH x: f "SEH" (BINOP_LR x)
    | SH x: f "SH" (BINOP_RR x)
    | SHE x: f "SHE" (BINOP_RR x)
    | SLL x: f "SLL" (TERNOP_LRR x)
    | SLLV x: f "SLLV" (TERNOP_LRR x)
    | SLT x: f "SLT" (TERNOP_LRR x)
    | SLTI x: f "SLTI" (TERNOP_LRR x)
    | SLTIU x: f "SLTIU" (TERNOP_LRR x)
    | SLTU x: f "SLTU" (TERNOP_LRR x)
    | SQRT-fmt x: f "SQRT" (BINOP_FLR x)
    | SRA x: f "SRA" (TERNOP_LRR x)
    | SRAV x: f "SRAV" (TERNOP_LRR x)
    | SRL x: f "SRL" (TERNOP_LRR x)
    | SRLV x: f "SRLV" (TERNOP_LRR x)
    | SUB x: f "SUB" (TERNOP_LRR x)
    | SUB-fmt x: f "SUB" (TERNOP_FLRR x)
    | SUBU x: f "SUBU" (TERNOP_LRR x)
    | SUXC1 x: f "SUXC1" (BINOP_RR x)
    | SW x: f "SW" (BINOP_RR x)
    | SWC1 x: f "SWC1" (BINOP_RR x)
    | SWC2 x: f "SWC2" (BINOP_RR x)
    | SWE x: f "SWE" (BINOP_RR x)
    | SWL x: f "SWL" (BINOP_RR x)
    | SWLE x: f "SWLE" (BINOP_RR x)
    | SWR x: f "SWR" (BINOP_RR x)
    | SWRE x: f "SWRE" (BINOP_RR x)
    | SWXC1 x: f "SWXC1" (BINOP_RR x)
    | SYNC x: f "SYNC" (UNOP_R x)
    | SYNCI x: f "SYNCI" (BINOP_RR x)
    | SYSCALL x: f "SYSCALL" (UNOP_R x)
    | TEQ x: f "TEQ" (TERNOP_RRR x)
    | TEQI x: f "TEQI" (BINOP_RR x)
    | TGE x: f "TGE" (TERNOP_RRR x)
    | TGEI x: f "TGEI" (BINOP_RR x)
    | TGEIU x: f "TGEIU" (BINOP_RR x)
    | TGEU x: f "TGEU" (TERNOP_RRR x)
    | TLBINV: f "TLBINV" (NULLOP)
    | TLBINVF: f "TLBINVF" (NULLOP)
    | TLBP: f "TLBP" (NULLOP)
    | TLBR: f "TLBR" (NULLOP)
    | TLBWI: f "TLBWI" (NULLOP)
    | TLBWR: f "TLBWR" (NULLOP)
    | TLT x: f "TLT" (TERNOP_RRR x)
    | TLTI x: f "TLTI" (BINOP_RR x)
    | TLTIU x: f "TLTIU" (BINOP_RR x)
    | TLTU x: f "TLTU" (TERNOP_RRR x)
    | TNE x: f "TNE" (TERNOP_RRR x)
    | TNEI x: f "TNEI" (BINOP_RR x)
    | TRUNC-L-fmt x: f "TRUNC.L" (BINOP_FLR x)
    | TRUNC-W-fmt x: f "TRUNC.W" (BINOP_FLR x)
    | WAIT x: f "WAIT" (UNOP_R x)
    | WRPGPR x: f "WRPGPR" (BINOP_RR x)
    | WSBH x: f "WSBH" (BINOP_LR x)
    | XOR x: f "XOR" (TERNOP_LRR x)
    | XORI x: f "XORI" (TERNOP_LRR x)
   end


# <- sutl

