/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeInterface */

#ifndef _Included_NativeInterface
#define _Included_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeInterface
 * Method:    decodeAndTranslateNative
 * Signature: ([B)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_NativeInterface_decodeAndTranslateNative
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
