/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rnati_NativeInterface */

#ifndef _Included_rnati_NativeInterface
#define _Included_rnati_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rnati_NativeInterface
 * Method:    decodeAndTranslateNative
 * Signature: ([B)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_rnati_NativeInterface_decodeAndTranslateNative
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
