/**
 * generated by Xtext
 */
package gdsl.plugin.generator;

import gdsl.plugin.generator.RunCompiler;
import gdsl.plugin.preferences.plugin.GDSLPluginPreferences;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class GDSLGenerator implements IGenerator {
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    StringBuilder commandBuilder = new StringBuilder();
    commandBuilder.append("echo ");
    String _outputName = GDSLPluginPreferences.getOutputName(resource);
    commandBuilder.append(_outputName);
    String _string = commandBuilder.toString();
    RunCompiler.compile(_string);
  }
}
