/**
 * generated by Xtext
 */
package gdsl.plugin.ui.contentassist;

import gdsl.plugin.ui.contentassist.AbstractGDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class GDSLProposalProvider extends AbstractGDSLProposalProvider {
}
