/*
* generated by Xtext
*/
package gdsl.plugin.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import gdsl.plugin.services.GDSLGrammarAccess;

public class GDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private GDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected gdsl.plugin.ui.contentassist.antlr.internal.InternalGDSLParser createParser() {
		gdsl.plugin.ui.contentassist.antlr.internal.InternalGDSLParser result = new gdsl.plugin.ui.contentassist.antlr.internal.InternalGDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDeclAccess().getAlternatives(), "rule__Decl__Alternatives");
					put(grammarAccess.getDeclTypeAccess().getAlternatives_2(), "rule__DeclType__Alternatives_2");
					put(grammarAccess.getDeclTypeAccess().getAlternatives_2_0(), "rule__DeclType__Alternatives_2_0");
					put(grammarAccess.getDeclValAccess().getAlternatives(), "rule__DeclVal__Alternatives");
					put(grammarAccess.getDeclValAccess().getAlternatives_0_1(), "rule__DeclVal__Alternatives_0_1");
					put(grammarAccess.getDeclValAccess().getAlternatives_1_5(), "rule__DeclVal__Alternatives_1_5");
					put(grammarAccess.getTyAccess().getAlternatives(), "rule__Ty__Alternatives");
					put(grammarAccess.getDecodePatAccess().getAlternatives(), "rule__DecodePat__Alternatives");
					put(grammarAccess.getTokPatAccess().getTokPatAlternatives_0(), "rule__TokPat__TokPatAlternatives_0");
					put(grammarAccess.getPrimBitPatAccess().getAlternatives(), "rule__PrimBitPat__Alternatives");
					put(grammarAccess.getBitPatOrIntAccess().getAlternatives(), "rule__BitPatOrInt__Alternatives");
					put(grammarAccess.getIntAccess().getAlternatives(), "rule__Int__Alternatives");
					put(grammarAccess.getPOSINTAccess().getAlternatives(), "rule__POSINT__Alternatives");
					put(grammarAccess.getHEXDIGITAccess().getAlternatives(), "rule__HEXDIGIT__Alternatives");
					put(grammarAccess.getHEXCHARAccess().getAlternatives(), "rule__HEXCHAR__Alternatives");
					put(grammarAccess.getULETTERAccess().getAlternatives(), "rule__ULETTER__Alternatives");
					put(grammarAccess.getLETTERAccess().getAlternatives(), "rule__LETTER__Alternatives");
					put(grammarAccess.getIDCHARAccess().getAlternatives(), "rule__IDCHAR__Alternatives");
					put(grammarAccess.getBINARYAccess().getAlternatives(), "rule__BINARY__Alternatives");
					put(grammarAccess.getDIGAccess().getAlternatives(), "rule__DIG__Alternatives");
					put(grammarAccess.getSYMAccess().getAlternatives(), "rule__SYM__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModelAccess().getGroup_1(), "rule__Model__Group_1__0");
					put(grammarAccess.getDeclGranularityAccess().getGroup(), "rule__DeclGranularity__Group__0");
					put(grammarAccess.getDeclExportAccess().getGroup(), "rule__DeclExport__Group__0");
					put(grammarAccess.getDeclTypeAccess().getGroup(), "rule__DeclType__Group__0");
					put(grammarAccess.getDeclTypeAccess().getGroup_2_0_0(), "rule__DeclType__Group_2_0_0__0");
					put(grammarAccess.getDeclTypeAccess().getGroup_2_1(), "rule__DeclType__Group_2_1__0");
					put(grammarAccess.getDeclTypeAccess().getGroup_2_1_2(), "rule__DeclType__Group_2_1_2__0");
					put(grammarAccess.getDeclValAccess().getGroup_0(), "rule__DeclVal__Group_0__0");
					put(grammarAccess.getDeclValAccess().getGroup_1(), "rule__DeclVal__Group_1__0");
					put(grammarAccess.getDeclValAccess().getGroup_1_3(), "rule__DeclVal__Group_1_3__0");
					put(grammarAccess.getDeclValAccess().getGroup_1_5_0(), "rule__DeclVal__Group_1_5_0__0");
					put(grammarAccess.getDeclValAccess().getGroup_1_5_1(), "rule__DeclVal__Group_1_5_1__0");
					put(grammarAccess.getExportAccess().getGroup(), "rule__Export__Group__0");
					put(grammarAccess.getExportAccess().getGroup_1(), "rule__Export__Group_1__0");
					put(grammarAccess.getExportAccess().getGroup_1_2(), "rule__Export__Group_1_2__0");
					put(grammarAccess.getConDeclsAccess().getGroup(), "rule__ConDecls__Group__0");
					put(grammarAccess.getConDeclsAccess().getGroup_1(), "rule__ConDecls__Group_1__0");
					put(grammarAccess.getConDeclAccess().getGroup(), "rule__ConDecl__Group__0");
					put(grammarAccess.getConDeclAccess().getGroup_1(), "rule__ConDecl__Group_1__0");
					put(grammarAccess.getTyAccess().getGroup_1(), "rule__Ty__Group_1__0");
					put(grammarAccess.getTyAccess().getGroup_2(), "rule__Ty__Group_2__0");
					put(grammarAccess.getTyAccess().getGroup_2_1(), "rule__Ty__Group_2_1__0");
					put(grammarAccess.getTyAccess().getGroup_2_1_2(), "rule__Ty__Group_2_1_2__0");
					put(grammarAccess.getTyAccess().getGroup_3(), "rule__Ty__Group_3__0");
					put(grammarAccess.getTyAccess().getGroup_3_2(), "rule__Ty__Group_3_2__0");
					put(grammarAccess.getTyElementAccess().getGroup(), "rule__TyElement__Group__0");
					put(grammarAccess.getTyBindAccess().getGroup(), "rule__TyBind__Group__0");
					put(grammarAccess.getTyBindAccess().getGroup_1(), "rule__TyBind__Group_1__0");
					put(grammarAccess.getBitPatAccess().getGroup(), "rule__BitPat__Group__0");
					put(grammarAccess.getPrimBitPatAccess().getGroup_1(), "rule__PrimBitPat__Group_1__0");
					put(grammarAccess.getBitPatOrIntAccess().getGroup_0(), "rule__BitPatOrInt__Group_0__0");
					put(grammarAccess.getBitPatOrIntAccess().getGroup_1(), "rule__BitPatOrInt__Group_1__0");
					put(grammarAccess.getNEGINTAccess().getGroup(), "rule__NEGINT__Group__0");
					put(grammarAccess.getHEXNUMAccess().getGroup(), "rule__HEXNUM__Group__0");
					put(grammarAccess.getMIXIDAccess().getGroup(), "rule__MIXID__Group__0");
					put(grammarAccess.getCONSAccess().getGroup(), "rule__CONS__Group__0");
					put(grammarAccess.getIDAccess().getGroup(), "rule__ID__Group__0");
					put(grammarAccess.getModelAccess().getDeclAssignment_0(), "rule__Model__DeclAssignment_0");
					put(grammarAccess.getModelAccess().getDeclAssignment_1_1(), "rule__Model__DeclAssignment_1_1");
					put(grammarAccess.getDeclGranularityAccess().getNameAssignment_0(), "rule__DeclGranularity__NameAssignment_0");
					put(grammarAccess.getDeclGranularityAccess().getGranularityAssignment_2(), "rule__DeclGranularity__GranularityAssignment_2");
					put(grammarAccess.getDeclExportAccess().getNameAssignment_0(), "rule__DeclExport__NameAssignment_0");
					put(grammarAccess.getDeclExportAccess().getExportsAssignment_2(), "rule__DeclExport__ExportsAssignment_2");
					put(grammarAccess.getDeclTypeAccess().getNameAssignment_1(), "rule__DeclType__NameAssignment_1");
					put(grammarAccess.getDeclTypeAccess().getValueAssignment_2_0_0_1(), "rule__DeclType__ValueAssignment_2_0_0_1");
					put(grammarAccess.getDeclTypeAccess().getValueAssignment_2_0_1(), "rule__DeclType__ValueAssignment_2_0_1");
					put(grammarAccess.getDeclTypeAccess().getAttrNameAssignment_2_1_1(), "rule__DeclType__AttrNameAssignment_2_1_1");
					put(grammarAccess.getDeclTypeAccess().getAttrNameAssignment_2_1_2_1(), "rule__DeclType__AttrNameAssignment_2_1_2_1");
					put(grammarAccess.getDeclTypeAccess().getValueAssignment_2_1_5(), "rule__DeclType__ValueAssignment_2_1_5");
					put(grammarAccess.getDeclValAccess().getNameAssignment_0_1_0(), "rule__DeclVal__NameAssignment_0_1_0");
					put(grammarAccess.getDeclValAccess().getNameAssignment_0_1_1(), "rule__DeclVal__NameAssignment_0_1_1");
					put(grammarAccess.getDeclValAccess().getAttrAssignment_0_2(), "rule__DeclVal__AttrAssignment_0_2");
					put(grammarAccess.getDeclValAccess().getExpAssignment_0_4(), "rule__DeclVal__ExpAssignment_0_4");
					put(grammarAccess.getDeclValAccess().getNameAssignment_1_1(), "rule__DeclVal__NameAssignment_1_1");
					put(grammarAccess.getDeclValAccess().getDecPatAssignment_1_3_0(), "rule__DeclVal__DecPatAssignment_1_3_0");
					put(grammarAccess.getDeclValAccess().getDecPatAssignment_1_3_1(), "rule__DeclVal__DecPatAssignment_1_3_1");
					put(grammarAccess.getDeclValAccess().getExpAssignment_1_5_0_1(), "rule__DeclVal__ExpAssignment_1_5_0_1");
					put(grammarAccess.getDeclValAccess().getExpsAssignment_1_5_1_1(), "rule__DeclVal__ExpsAssignment_1_5_1_1");
					put(grammarAccess.getDeclValAccess().getExpsAssignment_1_5_1_3(), "rule__DeclVal__ExpsAssignment_1_5_1_3");
					put(grammarAccess.getExportAccess().getNameAssignment_0(), "rule__Export__NameAssignment_0");
					put(grammarAccess.getExportAccess().getAttrNameAssignment_1_1(), "rule__Export__AttrNameAssignment_1_1");
					put(grammarAccess.getExportAccess().getAttrNameAssignment_1_2_1(), "rule__Export__AttrNameAssignment_1_2_1");
					put(grammarAccess.getConDeclsAccess().getConDeclsAssignment_0(), "rule__ConDecls__ConDeclsAssignment_0");
					put(grammarAccess.getConDeclsAccess().getConDeclsAssignment_1_1(), "rule__ConDecls__ConDeclsAssignment_1_1");
					put(grammarAccess.getConDeclAccess().getNameAssignment_0(), "rule__ConDecl__NameAssignment_0");
					put(grammarAccess.getConDeclAccess().getTyAssignment_1_1(), "rule__ConDecl__TyAssignment_1_1");
					put(grammarAccess.getTyAccess().getValueAssignment_0(), "rule__Ty__ValueAssignment_0");
					put(grammarAccess.getTyAccess().getValueAssignment_1_1(), "rule__Ty__ValueAssignment_1_1");
					put(grammarAccess.getTyAccess().getValueAssignment_2_0(), "rule__Ty__ValueAssignment_2_0");
					put(grammarAccess.getTyAccess().getTyBindAssignment_2_1_1(), "rule__Ty__TyBindAssignment_2_1_1");
					put(grammarAccess.getTyAccess().getTyBindAssignment_2_1_2_1(), "rule__Ty__TyBindAssignment_2_1_2_1");
					put(grammarAccess.getTyAccess().getElementsAssignment_3_1(), "rule__Ty__ElementsAssignment_3_1");
					put(grammarAccess.getTyAccess().getElementsAssignment_3_2_1(), "rule__Ty__ElementsAssignment_3_2_1");
					put(grammarAccess.getTyElementAccess().getNameAssignment_0(), "rule__TyElement__NameAssignment_0");
					put(grammarAccess.getTyElementAccess().getValueAssignment_2(), "rule__TyElement__ValueAssignment_2");
					put(grammarAccess.getTyBindAccess().getKeyAssignment_0(), "rule__TyBind__KeyAssignment_0");
					put(grammarAccess.getTyBindAccess().getValueAssignment_1_1(), "rule__TyBind__ValueAssignment_1_1");
					put(grammarAccess.getBitPatAccess().getBitpatAssignment_1(), "rule__BitPat__BitpatAssignment_1");
					put(grammarAccess.getBitPatAccess().getBitpatAssignment_2(), "rule__BitPat__BitpatAssignment_2");
					put(grammarAccess.getTokPatAccess().getTokPatAssignment(), "rule__TokPat__TokPatAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			gdsl.plugin.ui.contentassist.antlr.internal.InternalGDSLParser typedParser = (gdsl.plugin.ui.contentassist.antlr.internal.InternalGDSLParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public GDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
